import { z } from 'zod';

export const terminalExitSchema = z.object({
  exitCode: z.number().int().nullable(),
  signal: z.string().nullable(),
});
export type TerminalExit = z.infer<typeof terminalExitSchema>;

/**
 * Serializable snapshot of a managed terminal's state.
 * Returned by AcpRuntime.getTerminals() so that a renderer reload
 * can hydrate the full terminal list from the main-process authority without
 * replaying any event stream.
 */
export const terminalStateSchema = z.object({
  /** Stable id generated by the runtime for this terminal. */
  terminalId: z.string(),
  /** The command that was executed. */
  command: z.string(),
  /** Arguments passed to the command. */
  args: z.array(z.string()),
  /** Working directory the command ran in. */
  cwd: z.string(),
  /**
   * All output captured so far (stdout + stderr merged), encoded as UTF-8.
   * Respects the outputByteLimit ring-buffer; older bytes are discarded first.
   */
  output: z.string(),
  /** True when output was truncated due to the outputByteLimit cap. */
  truncated: z.boolean(),
  /** Non-null once the command has exited. */
  exitStatus: terminalExitSchema.nullable(),
});
export type TerminalState = z.infer<typeof terminalStateSchema>;
export const terminalSnapshotSchema = terminalStateSchema;
export type TerminalSnapshot = TerminalState;
