/**
 * claude-output-fixture — realistic assistant markdown covering every
 * construct Claude/Codex routinely emit, so one transcript exercises the
 * whole block/inline surface (see claude-output.contract.test.tsx).
 */

export const CLAUDE_OUTPUT_FIXTURE = [
  '# Migration plan',
  '',
  'Here is what I found after reading `src/relay/sync.ts` and the [RFC](https://example.com/rfc).',
  'It is **mostly** done, with a few _rough edges_ and one ~~blocker~~ non-issue (ignore the ~~[old RFC](https://example.com/old)~~).',
  '',
  '## Summary table',
  '',
  '| Area | Status | Owner |',
  '|------|:------:|------:|',
  '| Sync | done | @dylan |',
  '| Share | in progress | @ana |',
  '',
  '### Wide comparison',
  '',
  '| Option | Latency p50 | Latency p95 | Memory | Cold start | Bundle | License | Notes |',
  '|--------|------------:|------------:|-------:|-----------:|-------:|---------|-------|',
  '| `yjs` | 4ms | 18ms | 42MB | 120ms | 88kB | MIT | Mature, great awareness API |',
  '| `automerge` | 9ms | 31ms | 61MB | 210ms | 1.2MB | MIT | WASM core, heavier |',
  '| custom op-log | 2ms | 11ms | 12MB | 40ms | 14kB | — | We own it, but we also own every bug |',
  '',
  '#### Long cells ~~v1~~',
  '',
  '| Step | What happens |',
  '|------|--------------|',
  '| 1 | The relay receives the change, validates the signature against the workspace key, and appends it to the log before fanning it out to every connected peer. |',
  '| 2 | Peers apply the op; see [the protocol notes](https://example.com/protocol) and `applyOp()` for details. |',
  '',
  '| Key | Value |',
  '|-----|-------|',
  '| path | see `/Users/sam/Rig/growth/quarterly-planning/2026/q4/drafts/relay-sync-migration-notes-final-v3.md` |',
  '',
  '## Next steps',
  '',
  '1. Land the relay change',
  '   - bump `SKILL_VERSION`',
  '   - redeploy with `fly deploy`',
  '     1. check the health endpoint',
  '2. Ship the desktop build',
  '3. Announce it',
  '',
  '- [x] Write the migration',
  '- [ ] Backfill old workspaces',
  '- [ ] Update the docs',
  '',
  '> **Note:** the backfill is idempotent, so re-running it is safe.',
  '> It only touches rows with `version < 3`.',
  '>',
  '> - run it off-peak',
  '> - watch the dashboard',
  '>',
  '> ```sh',
  '> pnpm backfill --dry-run',
  '> ```',
  '>',
  '> Ping me if it fails.',
  '',
  '```ts',
  'export async function backfill(db: Db): Promise<number> {',
  "  const rows = await db.select().from(workspaces).where(lt(workspaces.version, 3)); // a deliberately long line that should scroll horizontally instead of wrapping",
  '  return rows.length;',
  '}',
  '```',
  '',
  '```',
  'plain fenced block without a language',
  '```',
  '',
  '---',
  '',
  'The formula is $O(n \\log n)$ in the worst case[^1].',
  '',
  '$$',
  'T(n) = 2T(n/2) + O(n)',
  '$$',
  '',
  '![Architecture diagram](https://example.com/diagram.png)',
  '',
  '```mermaid',
  'graph TD',
  '  A[Client] --> B[Relay]',
  '  B --> C[Peers]',
  '```',
  '',
  '[^1]: Assuming the log is already sorted.',
].join('\n');
