/**
 * codegen/emit-shiki.ts
 *
 * Emits theme/__generated__/shiki-themes.gen.ts — a single static, theme-
 * independent Shiki theme whose token colors reference CSS custom properties
 * (--syntax-<role>). Theme switching is achieved by swapping the .em<id> class,
 * which rebinds the vars via theme.css.
 *
 * Editor chrome colors that cannot be expressed as a plain var() in Shiki
 * (alpha-composited selection, findMatch, scrollbar) reference --syntax-editor-*
 * vars also emitted into theme.css. Non-alpha chrome reuses --background,
 * --foreground, and --neutral-* palette vars.
 */

import { nsVar } from '../contract/namespace';
import type { SyntaxRole } from '../contract/roles';
import { SYNTAX_TEMPLATE } from '../contract/syntax-template';

export function emitShikiThemesTs(): string {
  const tokenColors = (Object.keys(SYNTAX_TEMPLATE) as SyntaxRole[]).map((role) => {
    const entry = SYNTAX_TEMPLATE[role];
    const settings: Record<string, string> = { foreground: nsVar(`syntax-${role}`) };
    if (role === 'comment') settings['fontStyle'] = 'italic';
    return { scope: entry.scopes, settings };
  });

  const theme = {
    name: 'em-syntax',
    // 'light' and 'dark' are the two VSCode/Shiki polarity values; using 'light'
    // as the default is inert because all color values are CSS vars — the actual
    // polarity is determined by which .em<id> class is active on the root element.
    type: 'light',
    colors: {
      'editor.background': nsVar('background'),
      'editor.foreground': nsVar('foreground'),
      'editor.selectionBackground': nsVar('syntax-editor-selection-bg'),
      'editor.lineHighlightBackground': nsVar('neutral-2'),
      'editorCursor.foreground': nsVar('foreground'),
      'editor.findMatchBackground': nsVar('syntax-editor-find-match-bg'),
      'editor.findMatchHighlightBackground': nsVar('syntax-editor-find-match-hl'),
      'editorLineNumber.foreground': nsVar('neutral-9'),
      'editorLineNumber.activeForeground': nsVar('foreground'),
      'editorIndentGuide.background': nsVar('neutral-5'),
      'editorBracketMatch.background': nsVar('neutral-4'),
      'editorBracketMatch.border': nsVar('neutral-7'),
      'scrollbarSlider.background': nsVar('syntax-editor-scrollbar-bg'),
      'scrollbarSlider.hoverBackground': nsVar('syntax-editor-scrollbar-hover'),
    },
    tokenColors,
    semanticHighlighting: true,
  };

  return `// Generated by packages/ui/src/theme/core/codegen/run.ts. DO NOT EDIT.
// Single var-based Shiki theme. Token colors reference --syntax-* CSS custom
// properties; switching themes requires only a class swap on the root element.
// Import via @emdash/ui/theme/shiki-themes.

export const emSyntaxTheme = ${JSON.stringify(theme, null, 2)} as const;

export type EmSyntaxTheme = typeof emSyntaxTheme;
`;
}
