/**
 * codegen/emit-semantic-css.ts
 *
 * Emits theme/__generated__/semantic.css — one per-theme block of semantic slot vars only,
 * wrapped in @layer tokens. Consumed by hosts that import theme.css + semantic.css
 * separately.
 */

import { nsName } from '../contract/namespace';
import { SEMANTIC_TEMPLATE } from '../contract/semantic-template';
import type { ResolvedTheme } from '../define-theme';

export function emitSemanticCss(themes: ResolvedTheme[]): string {
  const semanticSlots = Object.keys(SEMANTIC_TEMPLATE).map((k) => nsName(k));
  const lines: string[] = [
    '/* Semantic color token aliases per theme.',
    ' * Import after theme.css. Generated by packages/ui/src/theme/core/codegen/run.ts */',
    '',
    '@layer tokens {',
  ];

  for (const theme of themes) {
    lines.push(`  ${theme.selector} {`);
    for (const slot of semanticSlots) {
      const value = theme.cssVars[slot];
      if (value != null) lines.push(`    ${slot}: ${value};`);
    }
    lines.push('  }', '');
  }

  lines.push('}');
  return lines.join('\n');
}
