import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    acp: 'src/acp/index.ts',
    'acp-client': 'src/acp/client.ts',
    'acp-transcript-parser': 'src/acp/reducer/index.ts',
    deps: 'src/host-dependencies/capability.ts',
    'deps-runtime': 'src/host-dependencies/runtime/index.ts',
    mcp: 'src/mcp/index.ts',
    skills: 'src/skills/index.ts',
    exec: 'src/exec/index.ts',
    files: 'src/files/index.ts',
    'services-fs-watch-api': 'src/services/fs-watch/api/index.ts',
    'services-fs-watch-worker': 'src/services/fs-watch/worker/index.ts',
    git: 'src/git/index.ts',
    lib: 'src/lib/index.ts',
    pty: 'src/pty/index.ts',
    'pty-node': 'src/pty/node/index.ts',
    'agents-agent-env': 'src/agents/agent-env.ts',
    'agents-spawn-context': 'src/agents/spawn-context.ts',
    'agents-plugins': 'src/agents/plugins/index.ts',
    'agents-plugins-helpers': 'src/agents/plugins/helpers/index.ts',
    'workspace-server': 'src/workspace-server/index.ts',
    'workspace-server-agent-config': 'src/workspace-server/agent-config/index.ts',
    'workspace-lifecycle': 'src/workspace-lifecycle/index.ts',
    'workspace-activity': 'src/workspace-activity/index.ts',
    'workspace-coordinator': 'src/workspace-coordinator/index.ts',
  },
  format: ['esm'],
  dts: true,
  deps: {
    neverBundle: [
      '@emdash/wire',
      'zod',
      '@parcel/watcher',
      'react',
      'smol-toml',
      'semver',
      'node-pty',
    ],
  },
  sourcemap: true,
  clean: true,
});
